### ISSUE TITLE
Use Case

### ISSUE THREAD

**Issue by smooJitter** [alexwasner/react-native-navigation-extra-view#1]
Can you please explain the use case of this package.   I have run into problems with RNN when trying to display swipe decks.  I can only get them to work on modal screens.  Does this offer a solution?

**Comment by alexwasner** [comment]
This is specifically to place a global view above the navigation stack. For example, if you want a button on every single screen of your app. For example, see [Flexdrive](https://itunes.apple.com/us/app/flexdrive-llc/id1212425636)
